### ISSUE TITLE
comment for your codes

### ISSUE THREAD

**Issue by ieee-wangwei** [Xu-yuan/BlackJack#1]
1.good explanation for your codes, the code contains many functions, the structure is clear.
2.you can use string to check this input, very good.
3.you can control the game runs more than one time.
4.use a good way to give the cards.

**Comment by cpxdudu** [comment]
I'm surprised by your procedure . The code is perfect and it can deal with all kinds of mistake. And the game is okay. Good job.

**Comment by Xu-yuan** [comment]
thanks for your comments.
